import java.util.List;

public class SongTitles {
    public  List<String> piesne;
    public  List<String> antifony;
    public  List<String> pasie;
    public  List<String> funebral;
    public  List<String> antifony_pohrebne;
    public  List<String> vecera_panova;
    public  List<String> dalsia_liturgia;
    public  List<String> informacie;

    public SongTitles(){
        piesne.clear();
        fillList_piesne();

        antifony.clear();
        fillList_antifony();

    }

    void fillList_piesne(){
        piesne.add(1,"Hospodine, nebeský Otče ... ML");
        piesne.add(2,"Hospodine, Pane ... TG");
        piesne.add(3,"Bože, ktorý si stvoril svet... TG");
        piesne.add(4,"Veríme v jedného Boha ... JL");
        piesne.add(5,"Bože Otče, láska večná");
        piesne.add(6,"Čím môžem Ťa privítať ... AH");
        piesne.add(7,"Čo Mária panna ... LF");
        piesne.add(8,"Hľa, už stojí predo dvermi");
        piesne.add(9,"Hosana! Už Kristus prišiel... LF");
        piesne.add(10,"Chvála Ti, Bože verný ... AH");
        piesne.add(11,"Mnohí svätí proroci ... TG");
        piesne.add(12,"Nad hviezd nebeských ... JR/Sk");
        piesne.add(13,"Ó, príď, Kriste");
        piesne.add(14,"Ó, príď, ó, príď, Emanuel ... OB/AŽ");
        piesne.add(15,"Otvárame, Pane Kriste");
        piesne.add(16,"Otvorte brány dokorán ... ML");
        piesne.add(17,"Prečo stojíš vonku ... AH");
        piesne.add(18,"Príď, Kriste, svetlo sveta... TG");
        piesne.add(19,"Príď, spasenie ... AH");
        piesne.add(20,"Prichádzaš k nám");
        piesne.add(21,"Púšťou sa nesie ... JR/AH/sl. 4-5");
        piesne.add(22,"Raduj sa a zaplesaj ... ZO/Sk");
        piesne.add(23,"Raduj sa, dcéra Sionská ... ZO");
        piesne.add(24,"Rosu dajte, ó nebesá ... BK/TG/sl. 5-9");
        piesne.add(25,"Sláva Bohu! Boží Syn... DOn");
        piesne.add(26,"Veselo spievajme ... ML");
        piesne.add(27,"Veseľte sa, veriaci ... ML");
        piesne.add(28,"Vitaj, Jezu Kriste ... ML");
        piesne.add(29,"V   plnosti času ... JL");
        piesne.add(30,"Vzácny čas ... JGL/Sk");
        piesne.add(31,"Bože večný, svetla zdroj ... TG");
        piesne.add(32,"Hospodine, Studnica dobroty ... ML");
        piesne.add(33,"Buď Bohu sláva ... DF/ML/sl. 2-4");
        piesne.add(34,"Sláva Ti buď, mocný Bože ... TG");
        piesne.add(35,"Boh je Boh jediný ... TG");
        piesne.add(36,"Veríme srdečne ... VB");
        piesne.add(37,"Aká veľká vec");
        piesne.add(38,"Anjeli z nebies výsosti ... JL");
        piesne.add(39,"Anjelov spev čujme ... FR");
        piesne.add(40,"Buď Bohu česť na výsosti, že ... ML");
        piesne.add(41,"Čas radosti ... JGL/ĽT/Sk");
        piesne.add(42,"Česť buď na výsostiach ... TG");
        piesne.add(43,"Keď sa Kristus narodil ... AŽ");
        piesne.add(44,"Kristus, Kráľ náš ... TG");
        piesne.add(45,"Kristus, Syn Boží... AH");
        piesne.add(46,"Len Tebe srdce dávam ... TG");
        piesne.add(47,"Narodil sa Kristus Pán ... ML");
        piesne.add(48,"Narodil sa Vykupiteľ ... AH");
        piesne.add(49,"Nebo otvorené");
        piesne.add(50,"Nuž, kresťania ... AŽ");
        piesne.add(51,"Nuž, všetci verní... AŽ");
        piesne.add(52,"Ó kresťania, poďme");
        piesne.add(53,"Ó ty vianočný ... JGL/AŽ");
        piesne.add(54,"Pri jasliach stojím... AŽ/AH/ML");
        piesne.add(55,"Radujte sa, ó kresťania ... TG");
        piesne.add(56,"Radujte sa, srdečne ... ML");
        piesne.add(57,"Slnko z hviezdy už vyšlo ... AZ");
        piesne.add(58,"Srdečne sa radujme");
        piesne.add(59,"Synu Boží a ľudský ... DŠ");
        piesne.add(60,"Tichánoc ... JGL/JL");
        piesne.add(61,"Už sa nám púčik rozvil ... AZ");
        piesne.add(62,"V   nádhernej noci ... ML");
        piesne.add(63,"V  temne vzplála");
        piesne.add(64,"Až podnes nám pomáhal ... ML");
        piesne.add(65,"Česť vzdajme Pánu ... AH");
        piesne.add(66,"Rok starý zavierame ... TG");
        piesne.add(67,"Večný Bože v milosti ... JL");
        piesne.add(68,"Aj tohoto roku ... Sk");
        piesne.add(69,"Čuj naše prosby ... TG");
        piesne.add(70,"Daj, nech sa nám ... JM");
        piesne.add(71,"Hospodinu podajme ruku ... IK/ML/Sk");
        piesne.add(72,"Ježiš, meno ... TG");
        piesne.add(73,"Ježiš, to Dieťa ... AH");
        piesne.add(74,"Ľud Boží, vitaj");
        piesne.add(75,"Nový rok som zase dožil");
        piesne.add(76,"Rok nový zase k nám prišiel ... ML");
        piesne.add(77,"Povstaň a hľaď ... JL");
        piesne.add(78,"Chvála Tebe, Otče ... TG");
        piesne.add(79,"Prepusť, prepusť ... JGL/Sk");
        piesne.add(80,"Hospodine, náš milý Otče ... ML");
        piesne.add(81,"Hospodine, Ty si Boh svätý ... TG");
        piesne.add(82,"Veríme v jediného ... TG");
        piesne.add(83,"Verme v Boha jedného ... ML");
        piesne.add(84,"Ajhľa, práve Ježiš milý ... Sp/JL/sl. 2-7");
        piesne.add(85,"Aj za mňa si mrel ... TG");
        piesne.add(86,"Baránok, hľa... AH");
        piesne.add(87,"Čo si učinil... ML");
        piesne.add(88,"Dokonané ... TG");
        piesne.add(89,"Drahý Spasiteľ náš ... JL/MK");
        piesne.add(90,"Jezu Kriste, Pane milý ... JMa/Sk");
        piesne.add(91,"Jezu, Tvoje hrozné rany ... ML");
        piesne.add(92,"Ježiš, Pán života ... JGL/Sk");
        piesne.add(93,"Keď na kríži");
        piesne.add(94,"Kriste, muž bolesti ... ML");
        piesne.add(95,"Kto bol tak nevinný ... TG");
        piesne.add(96,"Ku krížu sa utiekam ... ML");
        piesne.add(97,"Láska svätá ... JR/LF");
        piesne.add(98,"Môj Ježiši ... JP");
        piesne.add(99,"Nebeský Pán ... Sp");
        piesne.add(100,"Nevinnosťpremilá ... AŽ/Sk");
        piesne.add(101,"Noc pokryla tiché stráne");
        piesne.add(102,"Ó Hlava ubolená ... ML");
        piesne.add(103,"Ó Ježiši, Kráľu tichý");
        piesne.add(104,"Ó krv drahá ... ML");
        piesne.add(105,"Pane, tisíckrát vítam Ta ... AH");
        piesne.add(106,"Päť studní je... JFa/OF");
        piesne.add(107,"Plesajme radostne, priatelia");
        piesne.add(108,"Pod kríž Tvoj padám");
        piesne.add(109,"Poďakujme Kristu Pánu ... TG");
        piesne.add(110,"Pred Tebou sa skláňame ... JL");
        piesne.add(111,"Rozmýšľajme dnes ... TG");
        piesne.add(112,"Smutný čas ... JK");
        piesne.add(113,"Tam na kríži");
        piesne.add(114,"Ten na kríži ... TG");
        piesne.add(115,"Umučenie drahého ... AZ");
        piesne.add(116,"V   smutnej chvíli");
        piesne.add(117,"V  tomto tichom");
        piesne.add(118,"Vznes sa k Bohu ... AŽ/Sk");
        piesne.add(119,"Vždy, keď sa hriechov desím ... ML");
        piesne.add(120,"Zakvíľ. spev môj ...AH");
        piesne.add(121,"Bože Otče, Ty si mocne ... ML");
        piesne.add(122,"Hospodine, Bože Otče ... TG");
        piesne.add(123,"Sláva a česť ... ML");
        piesne.add(124,"Sláva Bohu, sláva ... TG");
        piesne.add(125,"Veríme v Boha večného, Stvoriteľa ... TG");
        piesne.add(126,"Veríme vo všemocného ... ML");
        piesne.add(127,"Bremeno ťažké ... AŽ/TG");
        piesne.add(128,"Darmo plesá ... Sk");
        piesne.add(129,"Deň vzkriesenia Pánovho ... AZ");
        piesne.add(130,"Haleluja! Chválime Ťa");
        piesne.add(131,"Haleluja! Chvály znejte");
        piesne.add(132,"Ja viem, že žije ... IK");
        piesne.add(133,"Jezu Kriste, Vykupiteľu ... JGL");
        piesne.add(134,"Ježiš Kristus Nazaretský ... AŽ");
        piesne.add(135,"Ježiš v tretí deň vstal ... TG");
        piesne.add(136,"Ježiš žije ... ML/JL");
        piesne.add(137,"Kristus Pán vstal, radujme sa ... JL");
        piesne.add(138,"Kristus Pán vstal slávne");
        piesne.add(139,"Kristus Pán vstal z mŕtvych ... JGL");
        piesne.add(140,"Kristus žije, život náš ... JL");
        piesne.add(141,"Nastal nám čas ... ML/JR/sl. 4");
        piesne.add(142,"Nebojte sa, nedeste sa ... OA");
        piesne.add(143,"Ó kresťania, vzdajme chválu ... TG");
        piesne.add(144,"Ó Slnko žitia môjho");
        piesne.add(145,"Pokoj vám ... TG");
        piesne.add(146,"Slnko svetlom nádherným ... ML");
        piesne.add(147,"Už skvie sa ráno ... LF/KW");
        piesne.add(148,"Veseľ sa, celý svet... JL");
        piesne.add(149,"Vitaj, Víťaz náš ... ML");
        piesne.add(150,"Víťaz nad smrťou ... AŽ");
        piesne.add(151,"Vrúcne všetci plesajme");
        piesne.add(152,"Vstal z mŕtvych ... ML");
        piesne.add(153,"Vstaň, srdce ... ML");
        piesne.add(154,"Všetci, čo túžite ... AŽ");
        piesne.add(155,"V  tretí deň Kristus z mŕtvych vstal ... KW");
        piesne.add(156,"Žije Ježiš ... AH");
        piesne.add(157,"Zmiluj sa, Bože ... ML");
        piesne.add(158,"Veríme všetci v jediného ... TG");
        piesne.add(159,"Do neba. do neba ... ML/MK/sl. 1");
        piesne.add(160,"Kriste, Spasiteľu náš ... Sk");
        piesne.add(161,"Náš Pán kraľuje, s Otcom ... BK/AŽ/sl. 2");
        piesne.add(162,"Natri miesta ... ML");
        piesne.add(163,"Pane môj, ja tu zostávam ... JL");
        piesne.add(164,"Slávne nebeské výšiny ... TG");
        piesne.add(165,"Bože Duchu dokonalý ... TG");
        piesne.add(166,"Bože, hriechy vyznávame ... ML");
        piesne.add(167,"Sláva Tebe, Duchu moci ... TG");
        piesne.add(168,"Sláva Ti buď na výsosti ... ML");
        piesne.add(169,"Boh je Duch ...TG");
        piesne.add(170,"Veríme všetci v Boha jedného ... ML");
        piesne.add(171,"Ako čerstvú vodu ... ML");
        piesne.add(172,"Duch Pánov ... TG");
        piesne.add(173,"Duch Svätý na učeníkov");
        piesne.add(174,"Duchu Svätý z výsosti ... Sk");
        piesne.add(175,"Ó, Duchom Svätým naplň nás");
        piesne.add(176,"Ó najsladšia moja radosť ... ML/AŽ/sl. 4");
        piesne.add(177,"Ó, príď, Duchu Svätý ... ML");
        piesne.add(178,"Príď, Duchu Svätý ... JDB");
        piesne.add(179,"Prosme vrúcne ... TG");
        piesne.add(180,"V  túžobnom očakávaní... TG");
        piesne.add(181,"Zošli Ducha Svätého nám ... ML");
        piesne.add(182,"Hľaďte, hľaďte ... ML");
        piesne.add(183,"O, prenesmierne bohatstvo");
        piesne.add(184,"Oslávme Boha svätého ... AH");
        piesne.add(185,"Teba dnes chválime ... MK");
        piesne.add(186,"Bože lásky, Otče ... TG");
        piesne.add(187,"Bože, Otče dobrotivý ... Sk");
        piesne.add(188,"Bože, Otče večnosti ... KW");
        piesne.add(189,"Hospodine, Stvoriteľ náš");
        piesne.add(190,"Hospodine, večný Pane");
        piesne.add(191,"Hospodine všemohúci ... ML");
        piesne.add(192,"Kyrieelejson ...TG");
        piesne.add(193,"Pane, zmiluj sa... KW");
        piesne.add(194,"Vieme to, Pane Bože náš ... AH");
        piesne.add(195,"Z hĺbky srdca ... AH");
        piesne.add(196,"My všetci veríme ... MK");
        piesne.add(197,"Veríme v Boha jediného ... AB");
        piesne.add(198,"Veríme v Boha jedného ... JP");
        piesne.add(199,"Veríme v Boha Stvoriteľa ... TG");
        piesne.add(200,"Veríme v Boha večného, On je ... JL");
        piesne.add(201,"Verme v Boha Otca ... ML");
        piesne.add(202,"Verme v mocného Boha ... JL");
        piesne.add(203,"V   jedného Boha veríme ... KW");
        piesne.add(204,"Všemohúci, Bože náš, Tebe");
        piesne.add(205,"Aké milé miesto ... ML");
        piesne.add(206,"Bože dobrý, svätý Pane ...TG");
        piesne.add(207,"Bože veľký od večnosti ... ML");
        piesne.add(208,"Bože, v tomto svätom chráme ... AH");
        piesne.add(209,"Keď svitol deň nedeľný");
        piesne.add(210,"Ódeňnedeľný ... FR");
        piesne.add(211,"Otvorte mi krásnu bránu ... ML");
        piesne.add(212,"O, vitaj v svojej jasnosti ... AH");
        piesne.add(213,"Svätým dňom je Pánov deň ... ML");
        piesne.add(214,"Vitaj nám, deň zasvätený ... JL");
        piesne.add(215,"Všetci my verní... AH");
        piesne.add(216,"Ježiši, Pane, skloň sa k nám ... JGL");
        piesne.add(217,"Milosrdný Bože náš ... TG");
        piesne.add(218,"Milý Pane ... ML");
        piesne.add(219,"Prišli sme, ó Ježiši");
        piesne.add(220,"Bože, buď požehnaný ... TG");
        piesne.add(221,"Bože večný, nepremenný");
        piesne.add(222,"Kráľ večný nás požehnaj ... MK");
        piesne.add(223,"Milosť Pána");
        piesne.add(224,"Poďakujme Pánovi... TG");
        piesne.add(225,"Sláva Ti buď, Bože náš ... TG");
        piesne.add(226,"Spev, prosby a kázanie ... ML");
        piesne.add(227,"Za dar slova");
        piesne.add(228,"Ako by som, Tvorca sveta ... JR");
        piesne.add(229,"Boh náš je láska");
        piesne.add(230,"Boh sa o mňa stará ... ZO/AZ");
        piesne.add(231,"Bože môj, pod Tvojím nebom ... TG");
        piesne.add(232,"Chváľ každý tvor Stvoriteľa ... JL");
        piesne.add(233,"Kráľu nebies");
        piesne.add(234,"Nech kamkoľvek pozriem ... TG");
        piesne.add(235,"Ó kresťania, chválu vzdajme ... JMn/MK");
        piesne.add(236,"Ó láska Božia v Kristu");
        piesne.add(237,"Pán Boh je prítomný ... TG");
        piesne.add(238,"Slávže, duša ... Sk");
        piesne.add(239,"Svätý od vekov ... AH");
        piesne.add(240,"Teba vďačne chválim");
        piesne.add(241,"Vševedúci Bože ... LK");
        piesne.add(242,"Jak tá jasná hviezda ... DOnATG");
        piesne.add(243,"Ježiši, Ty si od vekov ... MSa/AŽ");
        piesne.add(244,"Kristus, príklad pokory ... AŽ/MK");
        piesne.add(245,"Ó láska Božia, láska večná ... BK");
        piesne.add(246,"Pane, keď hľadím ... TG/JL");
        piesne.add(247,"Panuj, Kriste... TG");
        piesne.add(248,"Radosť moja ... TG/AŽ");
        piesne.add(249,"Tá pravda ma obživuje ... JR/AŽ");
        piesne.add(250,"Včera, dnes i na večnosť");
        piesne.add(251,"Duchu Svätý, Teba dnes");
        piesne.add(252,"Ó Duchu Svätý, žiadame všetci");
        piesne.add(253,"Otče náš, milý Pane ... ML");
        piesne.add(254,"Príď, ó, príď k nám ... JL");
        piesne.add(255,"Príď, Stvoriteľ ... TG");
        piesne.add(256,"Zavítaj z trónu svojho ... TG");
        piesne.add(257,"Zošli Ducha Svätého, keď ... AH");
        piesne.add(258,"Ach, Bože, zhliadni ... AŽ/ML");
        piesne.add(259,"Ach, zostaň, Kriste, s nami ... JL");
        piesne.add(260,"Bože veľký, milostivý ... AH");
        piesne.add(261,"Cirkev je chrám Najvyššieho ... ML");
        piesne.add(262,"Cirkev je chrámom ... AH");
        piesne.add(263,"Hradprepevný ... MK");
        piesne.add(264,"Ježiš je svojej ... TG");
        piesne.add(265,"Ježiši, Tvoje slovo ... ML");
        piesne.add(266,"Keby Pán Boh nebol s nami ... AH");
        piesne.add(267,"Kresťania, pamätajme ... AH");
        piesne.add(268,"Kriste, obranca ... ML");
        piesne.add(269,"Kriste, svoju si na skale ... JFa");
        piesne.add(270,"Milý Sion, upokoj sa ... JL");
        piesne.add(271,"Nezúfaj, stádočko malé ... JL/MK");
        piesne.add(272,"Od vekov v Teba dúfali sme ... EBL");
        piesne.add(273,"Ó, príď už, príď, čas ... TG");
        piesne.add(274,"Plesajme srdečne");
        piesne.add(275,"Pri spomienke ... TG/JL");
        piesne.add(276,"Sionkvíli...TG");
        piesne.add(277,"Ty vieš, Bože ... ML");
        piesne.add(278,"Vzbuď ducha dávnych svedkov ... JL/AZ");
        piesne.add(279,"Boh je môj hrad ... JL");
        piesne.add(280,"Bože, Tvoje slovo ... TG");
        piesne.add(281,"Bože, Ty si mocným slovom ... AH");
        piesne.add(282,"Bože, Ty si svetla prameň ... TG");
        piesne.add(283,"Drahý Kriste, za to čisté ... AH");
        piesne.add(284,"Chráň ma, Pane ... ML");
        piesne.add(285,"Nech nám je Boh milostivý ... JL/AŽ");
        piesne.add(286,"Svetlo sveta ... MSa");
        piesne.add(287,"Všetci, ktorí milujete ... JH/AZ");
        piesne.add(288,"Zachovaj nás ... ML");
        piesne.add(289,"BožeaOtče... AŽ");
        piesne.add(290,"Kriste, Ty si ustanovil");
        piesne.add(291,"Meno kresťan");
        piesne.add(292,"Som v Tvoje meno ... ML");
        piesne.add(293,"Všetci sme z rodu nového ... TG");
        piesne.add(294,"Vypočuj našich prosieb hlas ... TG");
        piesne.add(295,"Z rozkazu Pána ... TG");
        piesne.add(296,"Ach, ja biedny, ja úbohý ... JH/AŽ");
        piesne.add(297,"Duša, draho vykúpená ... JH/AŽ");
        piesne.add(298,"Ježiša neopustím, duša ... TG");
        piesne.add(299,"Kresťania, stále ... AH");
        piesne.add(300,"Pane, Ty si nám nehodným ... ML/MK");
        piesne.add(301,"Pripravuj sa, duša ... ML/MK");
        piesne.add(302,"Tu je ticho");
        piesne.add(303,"Túžba moja, Ježiši ... TG");
        piesne.add(304,"Za Tvoju lásku ... TG");
        piesne.add(305,"Bože, prosbu čuj ... MSa");
        piesne.add(306,"Bože večný, prosíme Ťa ... TG");
        piesne.add(307,"Bože verný, Bože ... AŽ/ML");
        piesne.add(308,"Modli sa často... TG/AŽ");
        piesne.add(309,"Môj Bože, darcom si ... TG/Sk");
        piesne.add(310,"Nepoznám sladšie potešenie ... AH");
        piesne.add(311,"O Pane, počuj");
        piesne.add(312,"O všemohúci Bože náš ... DF");
        piesne.add(313,"Otče môj, tak vysoko si");
        piesne.add(314,"Otče náš milý nebeský ... AŽ/MK");
        piesne.add(315,"Svieť, svetlo, svieť... FR");
        piesne.add(316,"Tvoja milosť presahuje ... AŽ/MK");
        piesne.add(317,"V   modlitbe bývaj vytrvalý ... JFa/AŽ");
        piesne.add(318,"V  tichosti ...TG");
        piesne.add(319,"Žehnajúce ruky ... AH");
        piesne.add(320,"Ach, čo smutný ... JL");
        piesne.add(321,"Ach, ja biedny, úbohý ... JK/ML");
        piesne.add(322,"Ach, môj Bože ... AŽ/MK");
        piesne.add(323,"Ach, môj Bože, kto pomôže ... ML");
        piesne.add(324,"Ach, sladké slová ... ML/JL/sl. 4");
        piesne.add(325,"Blahoslavený je, ten ... AH");
        piesne.add(326,"Kajúcne so slzami... JL/ML/sl. 2-3");
        piesne.add(327,"Kde si, môj Ježiši ... AŽ");
        piesne.add(328,"Ľutujem, že som zhrešil... TG");
        piesne.add(329,"Nespomínaj, Bože");
        piesne.add(330,"Ó drahý Kriste, Pane môj");
        piesne.add(331,"Odvráť, ó Bože ... AH");
        piesne.add(332,"Pokánie čiňme ... TG");
        piesne.add(333,"Srdce čisté, stvor mi ... TG");
        piesne.add(334,"Z hlbokosti k Tebe volám ... JGL/AŽ");
        piesne.add(335,"Zmiluj sa a zľutuj sa ... ML");
        piesne.add(336,"Bože, od Teba všetko máme ... ML");
        piesne.add(337,"Buď Bohu česť na výsosti za ... AŽ");
        piesne.add(338,"Buď chvála Tebe, Bože ... AH/TG");
        piesne.add(339,"Buď chvála Ti, Bože ... MSa");
        piesne.add(340,"Čo žiadaš od nás. Pane ... AH");
        piesne.add(341,"Ďakujte Bohu ... AŽ/ML");
        piesne.add(342,"Duša, Boha oslavuj, chváľ... TG ..");
        piesne.add(343,"Chvála Tebe, Bože náš");
        piesne.add(344,"Chváľ, duša ... ML");
        piesne.add(345,"Chváľme dnes Pána ... KW/AH");
        piesne.add(346,"Chváľte Boha večného ... ML");
        piesne.add(347,"Chváľte Hospodina ... AH");
        piesne.add(348,"Každý kvet");
        piesne.add(349,"Náš Pán kraľuje, slávne ... ML");
        piesne.add(350,"Nuž, Bohu ďakujme ... AH/Sk");
        piesne.add(351,"Nuž, všetci slávme ... ML");
        piesne.add(352,"Ó, by som tisíc jazykov mal ... ML");
        piesne.add(353,"Ó kresťania, Boha chváľme ... JR/TG");
        piesne.add(354,"Oslavuj, cirkev, Pána");
        piesne.add(355,"Oslavuj Pána... AŽ/AH/Sk");
        piesne.add(356,"Pánovi zvučne ... AH");
        piesne.add(357,"Sláva Bohu na výsosti ... TG");
        piesne.add(358,"Sláva Bohu Otcu");
        piesne.add(359,"Slávme Boha Otca");
        piesne.add(360,"Spievajte Bohu nové piesne ... LF");
        piesne.add(361,"Spievať pieseň novú ... ML");
        piesne.add(362,"Toto je deň");
        piesne.add(363,"Vďaka Ti, Bože, nebeský ... JV");
        piesne.add(364,"Vďaka Ti za žatvu, Bože");
        piesne.add(365,"Veľký si náš, Bože svätý");
        piesne.add(366,"Vznesme srdcia k výšinám");
        piesne.add(367,"Ako vtáča spevavé");
        piesne.add(368,"Bože Otče, buď Ti chvála ... ML");
        piesne.add(369,"Ďakujem, milý Pane... AŽ/TG/sl. 5");
        piesne.add(370,"Ďakujem Ti, ó Najvyšší... ML/TG");
        piesne.add(371,"Hospodine, počuj hlas môj ... TG");
        piesne.add(372,"Chvála buď na výsosti ... ML");
        piesne.add(373,"Ježiši milosrdný ... ML");
        piesne.add(374,"Keď zasvitnú ranné zore ... IK");
        piesne.add(375,"Minula nočná hodina ... TG/VB");
        piesne.add(376,"Môj Bože, opäť svetlo vidím ... TG");
        piesne.add(377,"Nádherný je svit... ML");
        piesne.add(378,"Ó duša, nespi");
        piesne.add(379,"Od východu jasné svetlo ... TG");
        piesne.add(380,"Opäť sme vstali ... AH");
        piesne.add(381,"Oslávme Pána ... AŽ");
        piesne.add(382,"Otče svetiel ... TG");
        piesne.add(383,"Pane mocný ... TG");
        piesne.add(384,"Prebuď sa, duša ... MK");
        piesne.add(385,"S Bohom začínam ... AH");
        piesne.add(386,"Slnko spravodlivosti ... AH");
        piesne.add(387,"Už slnko vychádza ... JFa");
        piesne.add(388,"Už svitá... DA/MK");
        piesne.add(389,"Už vidím s plesaním ... JL");
        piesne.add(390,"Vďaka Ti, ó Bože náš");
        piesne.add(391,"Vďaku Bohu vzdajme ... ML");
        piesne.add(392,"V   mene Ježišovom vstávam ... TG");
        piesne.add(393,"Vstali sme a hneď za rána ... ML");
        piesne.add(394,"V  tejto rannej chvíli ... AH");
        piesne.add(395,"Z celého srdca svojho ... AŽ/JL");
        piesne.add(396,"Zlatistý slnka jas ... JL");
        piesne.add(397,"Buď Hosťom naším ... Sk");
        piesne.add(398,"Otče náš, pri tomto stole ... ML");
        piesne.add(399,"Všemohúci Bože náš, Ty ... JGL/Sk");
        piesne.add(400,"Buď Ti chvála ... MK");
        piesne.add(401,"Ku Tebe, Otče ... JL");
        piesne.add(402,"Nuž chválu vzdajme Bohu ... MK");
        piesne.add(403,"Otče, všetko živé ... TG");
        piesne.add(404,"Príkladom Pána Ježiša ... ML");
        piesne.add(405,"Sláva buď Tebe, Bože náš ... JP");
        piesne.add(406,"Sviatočný deň");
        piesne.add(407,"Teba, Otče, vrúcne ctíme ... TG");
        piesne.add(408,"Tebe patrí vďaka ... ML");
        piesne.add(409,"Ach, jak všetko ... ML");
        piesne.add(410,"Bože náš, požehnaj");
        piesne.add(411,"Buď vďaka Tebe, Bože náš");
        piesne.add(412,"Ďakujeme, Ochranca náš ... AŽ");
        piesne.add(413,"Deň nedeľný sa končí zas ... ML/AZ");
        piesne.add(414,"Deň odchádza ... JL");
        piesne.add(415,"Deň zase pominul ... TG");
        piesne.add(416,"Dušamoja,rozpomeňsa...AŽ");
        piesne.add(417,"Hasne slnko");
        piesne.add(418,"Hľa, nastáva už nočný čas ... AH");
        piesne.add(419,"Ježiši, Spasiteľu môj ... AH");
        piesne.add(420,"Keď mesiac svieti krásne ... AH");
        piesne.add(421,"Keď sa priblížil ... TG");
        piesne.add(422,"Keď sme prácu .. .TG");
        piesne.add(423,"Končíme tento týždeň ... AŽ/MK");
        piesne.add(424,"Kriste, Ty si svetlo ... TG");
        piesne.add(425,"K večeru deň sa nachýlil ... ML");
        piesne.add(426,"Na lôžko idúc ... TG");
        piesne.add(427,"Na sklonku dňa ... AH");
        piesne.add(428,"Noc je predo dvermi ... LF");
        piesne.add(429,"Oči svoje už zavieram ... JL");
        piesne.add(430,"Pane dní a Pane nocí... DO/Sk");
        piesne.add(431,"Tmy šumia");
        piesne.add(432,"Utíchla už vrava");
        piesne.add(433,"Už zmĺkli. Bože, búrky");
        piesne.add(434,"Večerné keď zvony znejú ... AH");
        piesne.add(435,"V   podvečer, keď sa zmráka ... AH");
        piesne.add(436,"Za opatrovanie dobré ... LF");
        piesne.add(437,"Zas deň jeden z nášho žitia");
        piesne.add(438,"Zlaté slnko ... ĽF");
        piesne.add(439,"Zostaň pri nás ... FR/Sk");
        piesne.add(440,"Zostaň so mnou");
        piesne.add(441,"Ach či divne ... ML");
        piesne.add(442,"Blahoslavený človek je ... JL");
        piesne.add(443,"Človeče, chceš byť spasený... AH/TG");
        piesne.add(444,"Dobroty lásky plný ... ML/AŽ/MK");
        piesne.add(445,"Dopraj mi s Tebou ... AH");
        piesne.add(446,"Emanuel milý ... AŽ/JL");
        piesne.add(447,"Chcel by som, Bože ... JL");
        piesne.add(448,"Chcem Ťa milovať ... TG");
        piesne.add(449,"Jeden poklad ... TG");
        piesne.add(450,"Ježiša nenechám ... TG");
        piesne.add(451,"Ježiša neopustím, lebo ... Sk");
        piesne.add(452,"Ježiši, ako chceš ... TG/MK");
        piesne.add(453,"Ježiši, drahý poklad môj ... ZO");
        piesne.add(454,"Ježiši, keď sa Tvoja ... AŽ/MK");
        piesne.add(455,"Ježiši, nad med je sladšie ... ML");
        piesne.add(456,"Ježiši, Ty sám ... JL");
        piesne.add(457,"Ježiši, života môjho ... ML");
        piesne.add(458,"Ježiš ma miluje ... TG");
        piesne.add(459,"Ježiš, moja radosť... Sk");
        piesne.add(460,"Kdesi,môjpremilý... JK");
        piesne.add(461,"Kiež viac Ťa milujem ... VBa/sL 2/Sk");
        piesne.add(462,"K Tebe, Bože všemohúci, vzhliadam ... AH/MK/sl. 2.7");
        piesne.add(463,"Môjho Pána Ježiša ... JL");
        piesne.add(464,"Nádej, milá nádej ... AH");
        piesne.add(465,"Niet inej cesty");
        piesne.add(466,"Ó Ježiši Kriste");
        piesne.add(467,"Ó, nech mi nikto nehovorí... AH");
        piesne.add(468,"Ó, poďte ku mne všetci... AŽ");
        piesne.add(469,"O Synu Boží... LF");
        piesne.add(470,"Pamätaj, človeče ... JL");
        piesne.add(471,"Pán blahoslaví... LF/AŽ");
        piesne.add(472,"Rád poddávam sa ... JR/AŽ/MK");
        piesne.add(473,"Sám, Pane Bože ... Sk");
        piesne.add(474,"Skala vekov ... MR/MSa");
        piesne.add(475,"Smieť žiť pre Krista");
        piesne.add(476,"Takto volá ... AŽ");
        piesne.add(477,"Tri sú veci ... ML");
        piesne.add(478,"Tu som, Pane");
        piesne.add(479,"Volám k Tebe ... LF/JL");
        piesne.add(480,"V svete hriecha, bludu");
        piesne.add(481,"Všetci, čo skladajú ... ML");
        piesne.add(482,"V  Tebe, drahý Pane ... ML");
        piesne.add(483,"Vyznávaš kresťan som ... ML/AŽ/MK");
        piesne.add(484,"Za ruku veď ma, Pane ... JL/Sk");
        piesne.add(485,"Bože, Ty poznáš cesty ... AH");
        piesne.add(486,"Dobré koná ... JFa/ML/AŽ");
        piesne.add(487,"Kristova krv ... TG");
        piesne.add(488,"Kto v ochrane Najvyššieho ... LF/AŽ");
        piesne.add(489,"Ktože bude môcť žalovať... AH");
        piesne.add(490,"Mne dostalo sa zmilovania ... Sk");
        piesne.add(491,"Na Krista svoje hriechy ... JL/Sk");
        piesne.add(492,"Neopusť, duša moja ... AŽ");
        piesne.add(493,"Ó, veď ma sám ... MR/Sk");
        piesne.add(494,"Pán Boh sila moja... JKH");
        piesne.add(495,"Pane, vierou osvieť ma ... TG");
        piesne.add(496,"Viac bázne ... DA/LF");
        piesne.add(497,"Z nesmiernej Božej milosti ... JL");
        piesne.add(498,"Ži krásne ... KR");
        piesne.add(499,"Ach, Bože, vyslyš ... AH");
        piesne.add(500,"Aj keď ma Pán Boh zavše tresce ... ML");
        piesne.add(501,"Akže musím ... AŽ");
        piesne.add(502,"Akže sme už ... MK/ML/sl. 2");
        piesne.add(503,"Bohu zver svoje cesty ... AH/AŽ/MK");
        piesne.add(504,"Cez súženie k vykúpeniu ... TG");
        piesne.add(505,"Čímväčšíkríž...ML");
        piesne.add(506,"Čo Boh činí, to dobré je ...TG");
        piesne.add(507,"ČomôjBohchce...JGL/JFa/AZ");
        piesne.add(508,"Dosť. dosť už ... AH");
        piesne.add(509,"Dúfaj v Boha ... LF");
        piesne.add(510,"Dvíham oči ... JL");
        piesne.add(511,"Hospodine, Otče milý ... DF");
        piesne.add(512,"Hospodin sám je Pastier ... JL/Sk");
        piesne.add(513,"Ja v Boha milého ... IK/AŽ");
        piesne.add(514,"Keď kríž ma tlačí... JL");
        piesne.add(515,"Keď mi je srdce smutné ... TG");
        piesne.add(516,"Keď sa bieda ... ML");
        piesne.add(517,"Keď sa skúška viery blíži");
        piesne.add(518,"Keď v biedach ... AŽ/JL");
        piesne.add(519,"K Tebe, ó Bože môj ... MRs/Sk");
        piesne.add(520,"Kto dá mi sily");
        piesne.add(521,"Kto len na Boha sa spolieha ... AH");
        piesne.add(522,"Kvílim žalostivo ... TG");
        piesne.add(523,"Nermúť sa príliš ... TG");
        piesne.add(524,"Ó Pane, zmiluj sa nad nami ... TG");
        piesne.add(525,"Pán Boh mi je silou ... MK");
        piesne.add(526,"Pokorne, tíško ... AH/TG");
        piesne.add(527,"Prečo sa toľko rmútiš ... AH");
        piesne.add(528,"Strašná búrka ... AH .");
        piesne.add(529,"Stvoriteľ, Bože náš ... TG");
        piesne.add(530,"Tichosť, tichosť vôkol");
        piesne.add(531,"Vo všetkom počínaní... AH");
        piesne.add(532,"Teba som, ó môj Bože ... ML");
        piesne.add(533,"Zaslúžil som ... DŠ");
        piesne.add(534,"Bože, Tvoje prikázania ... AH");
        piesne.add(535,"Môj Bože, i keď Ty prebývaš ... ZO");
        piesne.add(536,"Môj Bože, Ty si až podnes ... LF");
        piesne.add(537,"Môj Otče dobrý ...TG/JL");
        piesne.add(538,"Prečože zabúdame ... TG");
        piesne.add(539,"V Bohu, srdce, teš sa ... AH");
        piesne.add(540,"Aké mám poslanie ... LF");
        piesne.add(541,"Ísť cestou striezlivosti... LF");
        piesne.add(542,"Keď Duch Svätý ... DF");
        piesne.add(543,"Ó Bože, daj mi z výsosti ... TG");
        piesne.add(544,"O spásu a život večný ... LF");
        piesne.add(545,"Srdce čisté, vierou živé ... JL");
        piesne.add(546,"Trpezlivosť mať musíš ... JR/ML/MK");
        piesne.add(547,"Aká ľúbezná ... TG");
        piesne.add(548,"Boh náš je Bohom lásky ... JFa");
        piesne.add(549,"Cnosť je sýtiť lačného ... TG");
        piesne.add(550,"Kriste, nech sa Ti podobný byť snažím ... DŠ");
        piesne.add(551,"Nedaj na hriech iných");
        piesne.add(552,"Ó láska večná ... TG");
        piesne.add(553,"Štedrý Darca");
        piesne.add(554,"Také mi srdce daj ... AŽ");
        piesne.add(555,"Bože, požehnaj z nebies");
        piesne.add(556,"Jak pekne je ... ML");
        piesne.add(557,"Ty sám si, Bože ... LF");
        piesne.add(558,"Bože, Otče všetkých ľudí... JH");
        piesne.add(559,"Ja a dom môj ... ML");
        piesne.add(560,"Môj Bože, ktorý učil si ma");
        piesne.add(561,"Muž, čo v bázni Božej stojí... JH");
        piesne.add(562,"Ak chceš ako kresťan ... DF");
        piesne.add(563,"Bože, vdaku Ti vzdávame");
        piesne.add(564,"Kto za pravdu horí");
        piesne.add(565,"Ó Pane drahý ... AŽ");
        piesne.add(566,"Za ľudí celého sveta ... JH");
        piesne.add(567,"Aby sme vždy ... TG");
        piesne.add(568,"Aj keď sme v mnohom rozdelení... ML");
        piesne.add(569,"Kristus Pán Východ nepozná ... EBL");
        piesne.add(570,"Tam z diaľnych sveta krajov ... ML");
        piesne.add(571,"Bože, daruj svetu pokoj ... AŽ");
        piesne.add(572,"Buď na zemi pokoj");
        piesne.add(573,"Daj, Bože. pokoja");
        piesne.add(574,"Horkpráci ... FR/Sk");
        piesne.add(575,"Ó Bože, Darca požehnania ... TG/sl. 2");
        piesne.add(576,"O Pane náš");
        piesne.add(577,"Začíname prácu");
        piesne.add(578,"Aj, prvý vzdych");
        piesne.add(579,"Chválime Ťa, Bože ... AH");
        piesne.add(580,"Ó, plesaj, cirkev");
        piesne.add(581,"Plesajme radostne, kresťania ... TG");
        piesne.add(582,"Pozdvihni sa na Sione");
        piesne.add(583,"Ó Bože, svojho požehnania");
        piesne.add(584,"Ó Kriste, Pastieru ... DF");
        piesne.add(585,"Zaplesaj, ľud");
        piesne.add(586,"Ó buď Ti chvála");
        piesne.add(587,"Ó, skloň sa z nebies ... TG");
        piesne.add(588,"Pane, Ty máš zaľúbenie ... ML");
        piesne.add(589,"Pohliadni na nás... ML");
        piesne.add(590,"Čuj, aká prekrásna pieseň... KR/VB");
        piesne.add(591,"Hej, pastieri");
        piesne.add(592,"Na nebesiach nad Betlemom");
        piesne.add(593,"Opolnoci ... KW");
        piesne.add(594,"Počúvajte, kresťania");
        piesne.add(595,"Prišiel k nám Boží Syn");
        piesne.add(596,"Sem sa, všetci");
        piesne.add(597,"Už Spasiteľ sa narodil ... JL");
        piesne.add(598,"Bol si tam");
        piesne.add(599,"Haleluja! Radostnú zvesť ... KW");
        piesne.add(600,"Kristus vstal z mŕtvych ... DOn");
        piesne.add(601,"Plesajme, kresťania... JV");
        piesne.add(602,"Raduj sa a plesaj ... KW");
        piesne.add(603,"Spasiteľu, Kriste ... DF");
        piesne.add(604,"Vezmi chlieb");
        piesne.add(605,"Vojdite, plesajme ... KW");
        piesne.add(606,"Žehnaj a ochraňuj nás ... BK");
        piesne.add(607,"Vďaka za toto krásne ráno ... OP");
        piesne.add(608,"Noc šíry už halí kraj");
        piesne.add(609,"Slnko za vrch zapadá ... AŽ");
        piesne.add(610,"Spánku čas ... KW/JL");
        piesne.add(611,"Ustatý som ... JL");
        piesne.add(612,"Už slnko zašlo ... VBa");
        piesne.add(613,"Absolón");
        piesne.add(614,"Blažený ten ...TG");
        piesne.add(615,"Boh nikdy slovo ... DF");
        piesne.add(616,"Boh stvoril svet... LF");
        piesne.add(617,"Hosana, Bože... JL");
        piesne.add(618,"Chváľte Pána Ježiša");
        piesne.add(619,"Ja vravím vtedy ... LF");
        piesne.add(620,"Keď Mojžiš s ľudom Božím");
        piesne.add(621,"Keď otvorím Písmo ... JV");
        piesne.add(622,"Keď rozsievač ... JL");
        piesne.add(623,"Knieža mieru ... JL");
        piesne.add(624,"K trónu slávy");
        piesne.add(625,"Mier na zemi... JMk/LF");
        piesne.add(626,"Muž múdry ...MR");
        piesne.add(627,"Na nebeských vtáčkov pozri ... JL");
        piesne.add(628,"Nebeský Bože, Tvorca ... JMk/LF");
        piesne.add(629,"Ó láska nesmierna ... AŽ");
        piesne.add(630,"On je kráľov Kráľ");
        piesne.add(631,"Pane, daruj mi");
        piesne.add(632,"Pane, chcem byť dobrý kresťan ,");
        piesne.add(633,"Pane, prúdom svojho žehnania ... MR");
        piesne.add(634,"Pane, vieru daj");
        piesne.add(635,"Pánovi znej spev ... JL");
        piesne.add(636,"Pomôž, Bože večný ... MK");
        piesne.add(637,"Predivná moc ... AH/LF");
        piesne.add(638,"Pre Krista v boj ...EM");
        piesne.add(639,"Prišiel Syn Boží");
        piesne.add(640,"Raz na púšti ... BK");
        piesne.add(641,"Spasiteľu, Pane môj ... JPk");
        piesne.add(642,"Šla svetom láska ... JMk/LF");
        piesne.add(643,"Taký, hľa, som ... AH");
        piesne.add(644,"Teba vzývam");
        piesne.add(645,"To ja, ó Pane môj");
        piesne.add(646,"Učiň ma, Bože ... KK");
        piesne.add(647,"V bludišti sveta ... LF/JMk");
        piesne.add(648,"Vezmi, Pane, život môj ... MRo");
        piesne.add(649,"V   srdciach nech nám ...MRo/MSa");
        piesne.add(650,"Všetci, čo sme ... BK/TG");
        piesne.add(651,"Výčitky ma sužujú");
        piesne.add(652,"Vzácna to a veľká radosť");
        piesne.add(653,"Za oných dávnych čias ... JL");
        piesne.add(654,"Zbohom si dajme ... MK");
        piesne.add(655,"Zhliadni na mňa ... GV/DA");
        piesne.add(656,"Kánony ... KW");
        piesne.add(657,"Žalmy");
        piesne.add(658,"Ach, milý Pane");
        piesne.add(659,"Aký biedny, aký krátky ... AŽ/MK");
        piesne.add(660,"Čas náš ako krásne leto ... AŽ/MK");
        piesne.add(661,"Čo sa toľko staráme ... AH");
        piesne.add(662,"HojžeBože");
        piesne.add(663,"Keď slnka jas ... AH");
        piesne.add(664,"Kto pozná čas ... ML/AŽ");
        piesne.add(665,"Márnosť vo svete ... JGL");
        piesne.add(666,"Musíme raz všetci umrieť ... AH");
        piesne.add(667,"Na poliach ... AH");
        piesne.add(668,"Nie svet a imanie ... JH");
        piesne.add(669,"Pane, jak chceš ... TG/ML");
        piesne.add(670,"Po nemnohých dňoch ... AH");
        piesne.add(671,"Prečo svet bojuje ... JL");
        piesne.add(672,"Svetská nádhera a sláva ... AŽ");
        piesne.add(673,"Všetci ľudia umrieť musia ... AŽ");
        piesne.add(674,"Bože, Pane večnosti... AŽ");
        piesne.add(675,"Dobrý boj som na svete ... AH");
        piesne.add(676,"Ja som pre večnosť ... TG");
        piesne.add(677,"Keď príde tá hodina ... JK");
        piesne.add(678,"Môj Bože, viem ... ML/TG");
        piesne.add(679,"Môj život je Kristus Pán ... ML");
        piesne.add(680,"Niet chvíle v živote ... PG");
        piesne.add(681,"Pane Kriste, to viem iste ... AŽ");
        piesne.add(682,"S tebou sa rozžehnávam ... TG");
        piesne.add(683,"Tak blahoslavený ... TG");
        piesne.add(684,"Duše všetkých verných ... AH");
        piesne.add(685,"Hviezda v noci... AH");
        piesne.add(686,"Keď Pán Ježiš k súdu príde... AH/sl. 6-7");
        piesne.add(687,"Ku koncu sa deň skláňa ... DA/AH");
        piesne.add(688,"Len do Tvojich rúk");
        piesne.add(689,"Mysli na súd ... TG");
        piesne.add(690,"Nemýľte sa");
        piesne.add(691,"Precitnite! Z veže znie hlas ... AH");
        piesne.add(692,"Spočívajte už v pokoji ... AH");
        piesne.add(693,"Utíšme plač ... DF/MLATG");
        piesne.add(694,"Už sa blíži ten čas ... TG");
        piesne.add(695,"Veľmi milujem Ťa, Pane ... JGL/AŽ");
        piesne.add(696,"Verím to pevne ... VPČ");
        piesne.add(697,"Viem ja, že v nebi ... ML/JL");
        piesne.add(698,"Vzkriesenie čakáme ... VPC");
        piesne.add(699,"Žiaľ, ešte neprišiel čas ... Sk");
        piesne.add(700,"Život je Boží dar");

    }
    void fillList_antifony(){
        antifony.add("1. - 10. Adventné");
        antifony.add("11. - 19. Vianočné");
        antifony.add("20. - 24. Na rozhraní rokov");
        antifony.add("25. - 31. Pôstne");
        antifony.add("32. - 37. Veľkonočné");
        antifony.add("38. - 40. Vstúpenie Krista Pána");
        antifony.add("41. - 45. Zoslanie Ducha Svätého");
        antifony.add("46. - 48. Trojjediný Boh");
        antifony.add("49. - 61. Nedele potrojičné");
        antifony.add("62. - 68. Cirkev a jej pôsobenie");
        antifony.add("69. - 75. Sviatosti");
        antifony.add("76. - 77. Poďakovanie za úrody");
        antifony.add("78. - 80. Kajúce dni");
        antifony.add("81. - 83. Pamiatka zosnulých");
        antifony.add("84. - 89. Iné");
    }
}


