var piesne = [
  "Hospodine, nebeský Otče ... ML",
  "Hospodine, Pane ... TG",
  "Bože, ktorý si stvoril svet... TG",
  "Veríme v jedného Boha ... JL",
  "Bože Otče, láska večná",
  "Čím môžem Ťa privítať ... AH",
  "Čo Mária panna ... LF",
  "Hľa, už stojí predo dvermi",
  "Hosana! Už Kristus prišiel... LF",
  "Chvála Ti, Bože verný ... AH",
  "Mnohí svätí proroci ... TG",
  "Nad hviezd nebeských ... JR/Sk",
  "Ó, príď, Kriste",
  "Ó, príď, ó, príď, Emanuel ... OB/AŽ",
  "Otvárame, Pane Kriste",
  "Otvorte brány dokorán ... ML",
  "Prečo stojíš vonku ... AH",
  "Príď, Kriste, svetlo sveta... TG",
  "Príď, spasenie ... AH",
  "Prichádzaš k nám",
  "Púšťou sa nesie ... JR/AH/sl. 4-5",
  "Raduj sa a zaplesaj ... ZO/Sk",
  "Raduj sa, dcéra Sionská ... ZO",
  "Rosu dajte, ó nebesá ... BK/TG/sl. 5-9",
  "Sláva Bohu! Boží Syn... DOn",
  "Veselo spievajme ... ML",
  "Veseľte sa, veriaci ... ML",
  "Vitaj, Jezu Kriste ... ML",
  "V   plnosti času ... JL",
  "Vzácny čas ... JGL/Sk",
  "Bože večný, svetla zdroj ... TG",
  "Hospodine, Studnica dobroty ... ML",
  "Buď Bohu sláva ... DF/ML/sl. 2-4",
  "Sláva Ti buď, mocný Bože ... TG",
  "Boh je Boh jediný ... TG",
  "Veríme srdečne ... VB",
  "Aká veľká vec",
  "Anjeli z nebies výsosti ... JL",
  "Anjelov spev čujme ... FR",
  "Buď Bohu česť na výsosti, že ... ML",
  "Čas radosti ... JGL/ĽT/Sk",
  "Česť buď na výsostiach ... TG",
  "Keď sa Kristus narodil ... AŽ",
  "Kristus, Kráľ náš ... TG",
  "Kristus, Syn Boží... AH",
  "Len Tebe srdce dávam ... TG",
  "Narodil sa Kristus Pán ... ML",
  "Narodil sa Vykupiteľ ... AH",
  "Nebo otvorené",
  "Nuž, kresťania ... AŽ",
  "Nuž, všetci verní... AŽ",
  "Ó kresťania, poďme",
  "Ó ty vianočný ... JGL/AŽ",
  "Pri jasliach stojím... AŽ/AH/ML",
  "Radujte sa, ó kresťania ... TG",
  "Radujte sa, srdečne ... ML",
  "Slnko z hviezdy už vyšlo ... AZ",
  "Srdečne sa radujme",
  "Synu Boží a ľudský ... DŠ",
  "Tichánoc ... JGL/JL",
  "Už sa nám púčik rozvil ... AZ",
  "V   nádhernej noci ... ML",
  "V  temne vzplála",
  "Až podnes nám pomáhal ... ML",
  "Česť vzdajme Pánu ... AH",
  "Rok starý zavierame ... TG",
  "Večný Bože v milosti ... JL",
  "Aj tohoto roku ... Sk",
  "Čuj naše prosby ... TG",
  "Daj, nech sa nám ... JM",
  "Hospodinu podajme ruku ... IK/ML/Sk",
  "Ježiš, meno ... TG",
  "Ježiš, to Dieťa ... AH",
  "Ľud Boží, vitaj",
  "Nový rok som zase dožil",
  "Rok nový zase k nám prišiel ... ML",
  "Povstaň a hľaď ... JL",
  "Chvála Tebe, Otče ... TG",
  "Prepusť, prepusť ... JGL/Sk",
  "Hospodine, náš milý Otče ... ML",
  "Hospodine, Ty si Boh svätý ... TG",
  "Veríme v jediného ... TG",
  "Verme v Boha jedného ... ML",
  "Ajhľa, práve Ježiš milý ... Sp/JL/sl. 2-7",
  "Aj za mňa si mrel ... TG",
  "Baránok, hľa... AH",
  "Čo si učinil... ML",
  "Dokonané ... TG",
  "Drahý Spasiteľ náš ... JL/MK",
  "Jezu Kriste, Pane milý ... JMa/Sk",
  "Jezu, Tvoje hrozné rany ... ML",
  "Ježiš, Pán života ... JGL/Sk",
  "Keď na kríži",
  "Kriste, muž bolesti ... ML",
  "Kto bol tak nevinný ... TG",
  "Ku krížu sa utiekam ... ML",
  "Láska svätá ... JR/LF",
  "Môj Ježiši ... JP",
  "Nebeský Pán ... Sp",
  "Nevinnosťpremilá ... AŽ/Sk",
  "Noc pokryla tiché stráne",
  "Ó Hlava ubolená ... ML",
  "Ó Ježiši, Kráľu tichý",
  "Ó krv drahá ... ML",
  "Pane, tisíckrát vítam Ta ... AH",
  "Päť studní je... JFa/OF",
  "Plesajme radostne, priatelia",
  "Pod kríž Tvoj padám",
  "Poďakujme Kristu Pánu ... TG",
  "Pred Tebou sa skláňame ... JL",
  "Rozmýšľajme dnes ... TG",
  "Smutný čas ... JK",
  "Tam na kríži",
  "Ten na kríži ... TG",
  "Umučenie drahého ... AZ",
  "V   smutnej chvíli",
  "V  tomto tichom",
  "Vznes sa k Bohu ... AŽ/Sk",
  "Vždy, keď sa hriechov desím ... ML",
  "Zakvíľ. spev môj ...AH",
  "Bože Otče, Ty si mocne ... ML",
  "Hospodine, Bože Otče ... TG",
  "Sláva a česť ... ML",
  "Sláva Bohu, sláva ... TG",
  "Veríme v Boha večného, Stvoriteľa ... TG",
  "Veríme vo všemocného ... ML",
  "Bremeno ťažké ... AŽ/TG",
  "Darmo plesá ... Sk",
  "Deň vzkriesenia Pánovho ... AZ",
  "Haleluja! Chválime Ťa",
  "Haleluja! Chvály znejte",
  "Ja viem, že žije ... IK",
  "Jezu Kriste, Vykupiteľu ... JGL",
  "Ježiš Kristus Nazaretský ... AŽ",
  "Ježiš v tretí deň vstal ... TG",
  "Ježiš žije ... ML/JL",
  "Kristus Pán vstal, radujme sa ... JL",
  "Kristus Pán vstal slávne",
  "Kristus Pán vstal z mŕtvych ... JGL",
  "Kristus žije, život náš ... JL",
  "Nastal nám čas ... ML/JR/sl. 4",
  "Nebojte sa, nedeste sa ... OA",
  "Ó kresťania, vzdajme chválu ... TG",
  "Ó Slnko žitia môjho",
  "Pokoj vám ... TG",
  "Slnko svetlom nádherným ... ML",
  "Už skvie sa ráno ... LF/KW",
  "Veseľ sa, celý svet... JL",
  "Vitaj, Víťaz náš ... ML",
  "Víťaz nad smrťou ... AŽ",
  "Vrúcne všetci plesajme",
  "Vstal z mŕtvych ... ML",
  "Vstaň, srdce ... ML",
  "Všetci, čo túžite ... AŽ",
  "V  tretí deň Kristus z mŕtvych vstal ... KW",
  "Žije Ježiš ... AH",
  "Zmiluj sa, Bože ... ML",
  "Veríme všetci v jediného ... TG",
  "Do neba. do neba ... ML/MK/sl. 1",
  "Kriste, Spasiteľu náš ... Sk",
  "Náš Pán kraľuje, s Otcom ... BK/AŽ/sl. 2",
  "Natri miesta ... ML",
  "Pane môj, ja tu zostávam ... JL",
  "Slávne nebeské výšiny ... TG",
  "Bože Duchu dokonalý ... TG",
  "Bože, hriechy vyznávame ... ML",
  "Sláva Tebe, Duchu moci ... TG",
  "Sláva Ti buď na výsosti ... ML",
  "Boh je Duch ...TG",
  "Veríme všetci v Boha jedného ... ML",
  "Ako čerstvú vodu ... ML",
  "Duch Pánov ... TG",
  "Duch Svätý na učeníkov",
  "Duchu Svätý z výsosti ... Sk",
  "Ó, Duchom Svätým naplň nás",
  "Ó najsladšia moja radosť ... ML/AŽ/sl. 4",
  "Ó, príď, Duchu Svätý ... ML",
  "Príď, Duchu Svätý ... JDB",
  "Prosme vrúcne ... TG",
  "V  túžobnom očakávaní... TG",
  "Zošli Ducha Svätého nám ... ML",
  "Hľaďte, hľaďte ... ML",
  "O, prenesmierne bohatstvo",
  "Oslávme Boha svätého ... AH",
  "Teba dnes chválime ... MK",
  "Bože lásky, Otče ... TG",
  "Bože, Otče dobrotivý ... Sk",
  "Bože, Otče večnosti ... KW",
  "Hospodine, Stvoriteľ náš",
  "Hospodine, večný Pane",
  "Hospodine všemohúci ... ML",
  "Kyrieelejson ...TG",
  "Pane, zmiluj sa... KW",
  "Vieme to, Pane Bože náš ... AH",
  "Z hĺbky srdca ... AH",
  "My všetci veríme ... MK",
  "Veríme v Boha jediného ... AB",
  "Veríme v Boha jedného ... JP",
  "Veríme v Boha Stvoriteľa ... TG",
  "Veríme v Boha večného, On je ... JL",
  "Verme v Boha Otca ... ML",
  "Verme v mocného Boha ... JL",
  "V   jedného Boha veríme ... KW",
  "Všemohúci, Bože náš, Tebe",
  "Aké milé miesto ... ML",
  "Bože dobrý, svätý Pane ...TG",
  "Bože veľký od večnosti ... ML",
  "Bože, v tomto svätom chráme ... AH",
  "Keď svitol deň nedeľný",
  "Ódeňnedeľný ... FR",
  "Otvorte mi krásnu bránu ... ML",
  "O, vitaj v svojej jasnosti ... AH",
  "Svätým dňom je Pánov deň ... ML",
  "Vitaj nám, deň zasvätený ... JL",
  "Všetci my verní... AH",
  "Ježiši, Pane, skloň sa k nám ... JGL",
  "Milosrdný Bože náš ... TG",
  "Milý Pane ... ML",
  "Prišli sme, ó Ježiši",
  "Bože, buď požehnaný ... TG",
  "Bože večný, nepremenný",
  "Kráľ večný nás požehnaj ... MK",
  "Milosť Pána",
  "Poďakujme Pánovi... TG",
  "Sláva Ti buď, Bože náš ... TG",
  "Spev, prosby a kázanie ... ML",
  "Za dar slova",
  "Ako by som, Tvorca sveta ... JR",
  "Boh náš je láska",
  "Boh sa o mňa stará ... ZO/AZ",
  "Bože môj, pod Tvojím nebom ... TG",
  "Chváľ každý tvor Stvoriteľa ... JL",
  "Kráľu nebies",
  "Nech kamkoľvek pozriem ... TG",
  "Ó kresťania, chválu vzdajme ... JMn/MK",
  "Ó láska Božia v Kristu",
  "Pán Boh je prítomný ... TG",
  "Slávže, duša ... Sk",
  "Svätý od vekov ... AH",
  "Teba vďačne chválim",
  "Vševedúci Bože ... LK",
  "Jak tá jasná hviezda ... DOnATG",
  "Ježiši, Ty si od vekov ... MSa/AŽ",
  "Kristus, príklad pokory ... AŽ/MK",
  "Ó láska Božia, láska večná ... BK",
  "Pane, keď hľadím ... TG/JL",
  "Panuj, Kriste... TG",
  "Radosť moja ... TG/AŽ",
  "Tá pravda ma obživuje ... JR/AŽ",
  "Včera, dnes i na večnosť",
  "Duchu Svätý, Teba dnes",
  "Ó Duchu Svätý, žiadame všetci",
  "Otče náš, milý Pane ... ML",
  "Príď, ó, príď k nám ... JL",
  "Príď, Stvoriteľ ... TG",
  "Zavítaj z trónu svojho ... TG",
  "Zošli Ducha Svätého, keď ... AH",
  "Ach, Bože, zhliadni ... AŽ/ML",
  "Ach, zostaň, Kriste, s nami ... JL",
  "Bože veľký, milostivý ... AH",
  "Cirkev je chrám Najvyššieho ... ML",
  "Cirkev je chrámom ... AH",
  "Hradprepevný ... MK",
  "Ježiš je svojej ... TG",
  "Ježiši, Tvoje slovo ... ML",
  "Keby Pán Boh nebol s nami ... AH",
  "Kresťania, pamätajme ... AH",
  "Kriste, obranca ... ML",
  "Kriste, svoju si na skale ... JFa",
  "Milý Sion, upokoj sa ... JL",
  "Nezúfaj, stádočko malé ... JL/MK",
  "Od vekov v Teba dúfali sme ... EBL",
  "Ó, príď už, príď, čas ... TG",
  "Plesajme srdečne",
  "Pri spomienke ... TG/JL",
  "Sionkvíli...TG",
  "Ty vieš, Bože ... ML",
  "Vzbuď ducha dávnych svedkov ... JL/AZ",
  "Boh je môj hrad ... JL",
  "Bože, Tvoje slovo ... TG",
  "Bože, Ty si mocným slovom ... AH",
  "Bože, Ty si svetla prameň ... TG",
  "Drahý Kriste, za to čisté ... AH",
  "Chráň ma, Pane ... ML",
  "Nech nám je Boh milostivý ... JL/AŽ",
  "Svetlo sveta ... MSa",
  "Všetci, ktorí milujete ... JH/AZ",
  "Zachovaj nás ... ML",
  "BožeaOtče... AŽ",
  "Kriste, Ty si ustanovil",
  "Meno kresťan",
  "Som v Tvoje meno ... ML",
  "Všetci sme z rodu nového ... TG",
  "Vypočuj našich prosieb hlas ... TG",
  "Z rozkazu Pána ... TG",
  "Ach, ja biedny, ja úbohý ... JH/AŽ",
  "Duša, draho vykúpená ... JH/AŽ",
  "Ježiša neopustím, duša ... TG",
  "Kresťania, stále ... AH",
  "Pane, Ty si nám nehodným ... ML/MK",
  "Pripravuj sa, duša ... ML/MK",
  "Tu je ticho",
  "Túžba moja, Ježiši ... TG",
  "Za Tvoju lásku ... TG",
  "Bože, prosbu čuj ... MSa",
  "Bože večný, prosíme Ťa ... TG",
  "Bože verný, Bože ... AŽ/ML",
  "Modli sa často... TG/AŽ",
  "Môj Bože, darcom si ... TG/Sk",
  "Nepoznám sladšie potešenie ... AH",
  "O Pane, počuj",
  "O všemohúci Bože náš ... DF",
  "Otče môj, tak vysoko si",
  "Otče náš milý nebeský ... AŽ/MK",
  "Svieť, svetlo, svieť... FR",
  "Tvoja milosť presahuje ... AŽ/MK",
  "V   modlitbe bývaj vytrvalý ... JFa/AŽ",
  "V  tichosti ...TG",
  "Žehnajúce ruky ... AH",
  "Ach, čo smutný ... JL",
  "Ach, ja biedny, úbohý ... JK/ML",
  "Ach, môj Bože ... AŽ/MK",
  "Ach, môj Bože, kto pomôže ... ML",
  "Ach, sladké slová ... ML/JL/sl. 4",
  "Blahoslavený je, ten ... AH",
  "Kajúcne so slzami... JL/ML/sl. 2-3",
  "Kde si, môj Ježiši ... AŽ",
  "Ľutujem, že som zhrešil... TG",
  "Nespomínaj, Bože",
  "Ó drahý Kriste, Pane môj",
  "Odvráť, ó Bože ... AH",
  "Pokánie čiňme ... TG",
  "Srdce čisté, stvor mi ... TG",
  "Z hlbokosti k Tebe volám ... JGL/AŽ",
  "Zmiluj sa a zľutuj sa ... ML",
  "Bože, od Teba všetko máme ... ML",
  "Buď Bohu česť na výsosti za ... AŽ",
  "Buď chvála Tebe, Bože ... AH/TG",
  "Buď chvála Ti, Bože ... MSa",
  "Čo žiadaš od nás. Pane ... AH",
  "Ďakujte Bohu ... AŽ/ML",
  "Duša, Boha oslavuj, chváľ... TG ..",
  "Chvála Tebe, Bože náš",
  "Chváľ, duša ... ML",
  "Chváľme dnes Pána ... KW/AH",
  "Chváľte Boha večného ... ML",
  "Chváľte Hospodina ... AH",
  "Každý kvet",
  "Náš Pán kraľuje, slávne ... ML",
  "Nuž, Bohu ďakujme ... AH/Sk",
  "Nuž, všetci slávme ... ML",
  "Ó, by som tisíc jazykov mal ... ML",
  "Ó kresťania, Boha chváľme ... JR/TG",
  "Oslavuj, cirkev, Pána",
  "Oslavuj Pána... AŽ/AH/Sk",
  "Pánovi zvučne ... AH",
  "Sláva Bohu na výsosti ... TG",
  "Sláva Bohu Otcu",
  "Slávme Boha Otca",
  "Spievajte Bohu nové piesne ... LF",
  "Spievať pieseň novú ... ML",
  "Toto je deň",
  "Vďaka Ti, Bože, nebeský ... JV",
  "Vďaka Ti za žatvu, Bože",
  "Veľký si náš, Bože svätý",
  "Vznesme srdcia k výšinám",
  "Ako vtáča spevavé",
  "Bože Otče, buď Ti chvála ... ML",
  "Ďakujem, milý Pane... AŽ/TG/sl. 5",
  "Ďakujem Ti, ó Najvyšší... ML/TG",
  "Hospodine, počuj hlas môj ... TG",
  "Chvála buď na výsosti ... ML",
  "Ježiši milosrdný ... ML",
  "Keď zasvitnú ranné zore ... IK",
  "Minula nočná hodina ... TG/VB",
  "Môj Bože, opäť svetlo vidím ... TG",
  "Nádherný je svit... ML",
  "Ó duša, nespi",
  "Od východu jasné svetlo ... TG",
  "Opäť sme vstali ... AH",
  "Oslávme Pána ... AŽ",
  "Otče svetiel ... TG",
  "Pane mocný ... TG",
  "Prebuď sa, duša ... MK",
  "S Bohom začínam ... AH",
  "Slnko spravodlivosti ... AH",
  "Už slnko vychádza ... JFa",
  "Už svitá... DA/MK",
  "Už vidím s plesaním ... JL",
  "Vďaka Ti, ó Bože náš",
  "Vďaku Bohu vzdajme ... ML",
  "V   mene Ježišovom vstávam ... TG",
  "Vstali sme a hneď za rána ... ML",
  "V  tejto rannej chvíli ... AH",
  "Z celého srdca svojho ... AŽ/JL",
  "Zlatistý slnka jas ... JL",
  "Buď Hosťom naším ... Sk",
  "Otče náš, pri tomto stole ... ML",
  "Všemohúci Bože náš, Ty ... JGL/Sk",
  "Buď Ti chvála ... MK",
  "Ku Tebe, Otče ... JL",
  "Nuž chválu vzdajme Bohu ... MK",
  "Otče, všetko živé ... TG",
  "Príkladom Pána Ježiša ... ML",
  "Sláva buď Tebe, Bože náš ... JP",
  "Sviatočný deň",
  "Teba, Otče, vrúcne ctíme ... TG",
  "Tebe patrí vďaka ... ML",
  "Ach, jak všetko ... ML",
  "Bože náš, požehnaj",
  "Buď vďaka Tebe, Bože náš",
  "Ďakujeme, Ochranca náš ... AŽ",
  "Deň nedeľný sa končí zas ... ML/AZ",
  "Deň odchádza ... JL",
  "Deň zase pominul ... TG",
  "Dušamoja,rozpomeňsa...AŽ",
  "Hasne slnko",
  "Hľa, nastáva už nočný čas ... AH",
  "Ježiši, Spasiteľu môj ... AH",
  "Keď mesiac svieti krásne ... AH",
  "Keď sa priblížil ... TG",
  "Keď sme prácu .. .TG",
  "Končíme tento týždeň ... AŽ/MK",
  "Kriste, Ty si svetlo ... TG",
  "K večeru deň sa nachýlil ... ML",
  "Na lôžko idúc ... TG",
  "Na sklonku dňa ... AH",
  "Noc je predo dvermi ... LF",
  "Oči svoje už zavieram ... JL",
  "Pane dní a Pane nocí... DO/Sk",
  "Tmy šumia",
  "Utíchla už vrava",
  "Už zmĺkli. Bože, búrky",
  "Večerné keď zvony znejú ... AH",
  "V   podvečer, keď sa zmráka ... AH",
  "Za opatrovanie dobré ... LF",
  "Zas deň jeden z nášho žitia",
  "Zlaté slnko ... ĽF",
  "Zostaň pri nás ... FR/Sk",
  "Zostaň so mnou",
  "Ach či divne ... ML",
  "Blahoslavený človek je ... JL",
  "Človeče, chceš byť spasený... AH/TG",
  "Dobroty lásky plný ... ML/AŽ/MK",
  "Dopraj mi s Tebou ... AH",
  "Emanuel milý ... AŽ/JL",
  "Chcel by som, Bože ... JL",
  "Chcem Ťa milovať ... TG",
  "Jeden poklad ... TG",
  "Ježiša nenechám ... TG",
  "Ježiša neopustím, lebo ... Sk",
  "Ježiši, ako chceš ... TG/MK",
  "Ježiši, drahý poklad môj ... ZO",
  "Ježiši, keď sa Tvoja ... AŽ/MK",
  "Ježiši, nad med je sladšie ... ML",
  "Ježiši, Ty sám ... JL",
  "Ježiši, života môjho ... ML",
  "Ježiš ma miluje ... TG",
  "Ježiš, moja radosť... Sk",
  "Kdesi,môjpremilý... JK",
  "Kiež viac Ťa milujem ... VBa/sL 2/Sk",
  "K Tebe, Bože všemohúci, vzhliadam ... AH/MK/sl. 2.7",
  "Môjho Pána Ježiša ... JL",
  "Nádej, milá nádej ... AH",
  "Niet inej cesty",
  "Ó Ježiši Kriste",
  "Ó, nech mi nikto nehovorí... AH",
  "Ó, poďte ku mne všetci... AŽ",
  "O Synu Boží... LF",
  "Pamätaj, človeče ... JL",
  "Pán blahoslaví... LF/AŽ",
  "Rád poddávam sa ... JR/AŽ/MK",
  "Sám, Pane Bože ... Sk",
  "Skala vekov ... MR/MSa",
  "Smieť žiť pre Krista",
  "Takto volá ... AŽ",
  "Tri sú veci ... ML",
  "Tu som, Pane",
  "Volám k Tebe ... LF/JL",
  "V svete hriecha, bludu",
  "Všetci, čo skladajú ... ML",
  "V  Tebe, drahý Pane ... ML",
  "Vyznávaš kresťan som ... ML/AŽ/MK",
  "Za ruku veď ma, Pane ... JL/Sk",
  "Bože, Ty poznáš cesty ... AH",
  "Dobré koná ... JFa/ML/AŽ",
  "Kristova krv ... TG",
  "Kto v ochrane Najvyššieho ... LF/AŽ",
  "Ktože bude môcť žalovať... AH",
  "Mne dostalo sa zmilovania ... Sk",
  "Na Krista svoje hriechy ... JL/Sk",
  "Neopusť, duša moja ... AŽ",
  "Ó, veď ma sám ... MR/Sk",
  "Pán Boh sila moja... JKH",
  "Pane, vierou osvieť ma ... TG",
  "Viac bázne ... DA/LF",
  "Z nesmiernej Božej milosti ... JL",
  "Ži krásne ... KR",
  "Ach, Bože, vyslyš ... AH",
  "Aj keď ma Pán Boh zavše tresce ... ML",
  "Akže musím ... AŽ",
  "Akže sme už ... MK/ML/sl. 2",
  "Bohu zver svoje cesty ... AH/AŽ/MK",
  "Cez súženie k vykúpeniu ... TG",
  "Čímväčšíkríž...ML",
  "Čo Boh činí, to dobré je ...TG",
  "ČomôjBohchce...JGL/JFa/AZ",
  "Dosť. dosť už ... AH",
  "Dúfaj v Boha ... LF",
  "Dvíham oči ... JL",
  "Hospodine, Otče milý ... DF",
  "Hospodin sám je Pastier ... JL/Sk",
  "Ja v Boha milého ... IK/AŽ",
  "Keď kríž ma tlačí... JL",
  "Keď mi je srdce smutné ... TG",
  "Keď sa bieda ... ML",
  "Keď sa skúška viery blíži",
  "Keď v biedach ... AŽ/JL",
  "K Tebe, ó Bože môj ... MRs/Sk",
  "Kto dá mi sily",
  "Kto len na Boha sa spolieha ... AH",
  "Kvílim žalostivo ... TG",
  "Nermúť sa príliš ... TG",
  "Ó Pane, zmiluj sa nad nami ... TG",
  "Pán Boh mi je silou ... MK",
  "Pokorne, tíško ... AH/TG",
  "Prečo sa toľko rmútiš ... AH",
  "Strašná búrka ... AH .",
  "Stvoriteľ, Bože náš ... TG",
  "Tichosť, tichosť vôkol",
  "Vo všetkom počínaní... AH",
  "Teba som, ó môj Bože ... ML",
  "Zaslúžil som ... DŠ",
  "Bože, Tvoje prikázania ... AH",
  "Môj Bože, i keď Ty prebývaš ... ZO",
  "Môj Bože, Ty si až podnes ... LF",
  "Môj Otče dobrý ...TG/JL",
  "Prečože zabúdame ... TG",
  "V Bohu, srdce, teš sa ... AH",
  "Aké mám poslanie ... LF",
  "Ísť cestou striezlivosti... LF",
  "Keď Duch Svätý ... DF",
  "Ó Bože, daj mi z výsosti ... TG",
  "O spásu a život večný ... LF",
  "Srdce čisté, vierou živé ... JL",
  "Trpezlivosť mať musíš ... JR/ML/MK",
  "Aká ľúbezná ... TG",
  "Boh náš je Bohom lásky ... JFa",
  "Cnosť je sýtiť lačného ... TG",
  "Kriste, nech sa Ti podobný byť snažím ... DŠ",
  "Nedaj na hriech iných",
  "Ó láska večná ... TG",
  "Štedrý Darca",
  "Také mi srdce daj ... AŽ",
  "Bože, požehnaj z nebies",
  "Jak pekne je ... ML",
  "Ty sám si, Bože ... LF",
  "Bože, Otče všetkých ľudí... JH",
  "Ja a dom môj ... ML",
  "Môj Bože, ktorý učil si ma",
  "Muž, čo v bázni Božej stojí... JH",
  "Ak chceš ako kresťan ... DF",
  "Bože, vdaku Ti vzdávame",
  "Kto za pravdu horí",
  "Ó Pane drahý ... AŽ",
  "Za ľudí celého sveta ... JH",
  "Aby sme vždy ... TG",
  "Aj keď sme v mnohom rozdelení... ML",
  "Kristus Pán Východ nepozná ... EBL",
  "Tam z diaľnych sveta krajov ... ML",
  "Bože, daruj svetu pokoj ... AŽ",
  "Buď na zemi pokoj",
  "Daj, Bože. pokoja",
  "Horkpráci ... FR/Sk",
  "Ó Bože, Darca požehnania ... TG/sl. 2",
  "O Pane náš",
  "Začíname prácu",
  "Aj, prvý vzdych",
  "Chválime Ťa, Bože ... AH",
  "Ó, plesaj, cirkev",
  "Plesajme radostne, kresťania ... TG",
  "Pozdvihni sa na Sione",
  "Ó Bože, svojho požehnania",
  "Ó Kriste, Pastieru ... DF",
  "Zaplesaj, ľud",
  "Ó buď Ti chvála",
  "Ó, skloň sa z nebies ... TG",
  "Pane, Ty máš zaľúbenie ... ML",
  "Pohliadni na nás... ML",
  "Čuj, aká prekrásna pieseň... KR/VB",
  "Hej, pastieri",
  "Na nebesiach nad Betlemom",
  "Opolnoci ... KW",
  "Počúvajte, kresťania",
  "Prišiel k nám Boží Syn",
  "Sem sa, všetci",
  "Už Spasiteľ sa narodil ... JL",
  "Bol si tam",
  "Haleluja! Radostnú zvesť ... KW",
  "Kristus vstal z mŕtvych ... DOn",
  "Plesajme, kresťania... JV",
  "Raduj sa a plesaj ... KW",
  "Spasiteľu, Kriste ... DF",
  "Vezmi chlieb",
  "Vojdite, plesajme ... KW",
  "Žehnaj a ochraňuj nás ... BK",
  "Vďaka za toto krásne ráno ... OP",
  "Noc šíry už halí kraj",
  "Slnko za vrch zapadá ... AŽ",
  "Spánku čas ... KW/JL",
  "Ustatý som ... JL",
  "Už slnko zašlo ... VBa",
  "Absolón",
  "Blažený ten ...TG",
  "Boh nikdy slovo ... DF",
  "Boh stvoril svet... LF",
  "Hosana, Bože... JL",
  "Chváľte Pána Ježiša",
  "Ja vravím vtedy ... LF",
  "Keď Mojžiš s ľudom Božím",
  "Keď otvorím Písmo ... JV",
  "Keď rozsievač ... JL",
  "Knieža mieru ... JL",
  "K trónu slávy",
  "Mier na zemi... JMk/LF",
  "Muž múdry ...MR",
  "Na nebeských vtáčkov pozri ... JL",
  "Nebeský Bože, Tvorca ... JMk/LF",
  "Ó láska nesmierna ... AŽ",
  "On je kráľov Kráľ",
  "Pane, daruj mi",
  "Pane, chcem byť dobrý kresťan ,",
  "Pane, prúdom svojho žehnania ... MR",
  "Pane, vieru daj",
  "Pánovi znej spev ... JL",
  "Pomôž, Bože večný ... MK",
  "Predivná moc ... AH/LF",
  "Pre Krista v boj ...EM",
  "Prišiel Syn Boží",
  "Raz na púšti ... BK",
  "Spasiteľu, Pane môj ... JPk",
  "Šla svetom láska ... JMk/LF",
  "Taký, hľa, som ... AH",
  "Teba vzývam",
  "To ja, ó Pane môj",
  "Učiň ma, Bože ... KK",
  "V bludišti sveta ... LF/JMk",
  "Vezmi, Pane, život môj ... MRo",
  "V   srdciach nech nám ...MRo/MSa",
  "Všetci, čo sme ... BK/TG",
  "Výčitky ma sužujú",
  "Vzácna to a veľká radosť",
  "Za oných dávnych čias ... JL",
  "Zbohom si dajme ... MK",
  "Zhliadni na mňa ... GV/DA",
  "Kánony ... KW",
  "Žalmy",
  "Ach, milý Pane",
  "Aký biedny, aký krátky ... AŽ/MK",
  "Čas náš ako krásne leto ... AŽ/MK",
  "Čo sa toľko staráme ... AH",
  "HojžeBože",
  "Keď slnka jas ... AH",
  "Kto pozná čas ... ML/AŽ",
  "Márnosť vo svete ... JGL",
  "Musíme raz všetci umrieť ... AH",
  "Na poliach ... AH",
  "Nie svet a imanie ... JH",
  "Pane, jak chceš ... TG/ML",
  "Po nemnohých dňoch ... AH",
  "Prečo svet bojuje ... JL",
  "Svetská nádhera a sláva ... AŽ",
  "Všetci ľudia umrieť musia ... AŽ",
  "Bože, Pane večnosti... AŽ",
  "Dobrý boj som na svete ... AH",
  "Ja som pre večnosť ... TG",
  "Keď príde tá hodina ... JK",
  "Môj Bože, viem ... ML/TG",
  "Môj život je Kristus Pán ... ML",
  "Niet chvíle v živote ... PG",
  "Pane Kriste, to viem iste ... AŽ",
  "S tebou sa rozžehnávam ... TG",
  "Tak blahoslavený ... TG",
  "Duše všetkých verných ... AH",
  "Hviezda v noci... AH",
  "Keď Pán Ježiš k súdu príde... AH/sl. 6-7",
  "Ku koncu sa deň skláňa ... DA/AH",
  "Len do Tvojich rúk",
  "Mysli na súd ... TG",
  "Nemýľte sa",
  "Precitnite! Z veže znie hlas ... AH",
  "Spočívajte už v pokoji ... AH",
  "Utíšme plač ... DF/MLATG",
  "Už sa blíži ten čas ... TG",
  "Veľmi milujem Ťa, Pane ... JGL/AŽ",
  "Verím to pevne ... VPČ",
  "Viem ja, že v nebi ... ML/JL",
  "Vzkriesenie čakáme ... VPC",
  "Žiaľ, ešte neprišiel čas ... Sk",
  "Život je Boží dar",
];